jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command:
            python -m unittest discover
          name: Test
orbs:
  python: circleci/python@1.1.0
version: 2.1
workflows:
  main:
    jobs:
      - build