jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: responses coverage
          pkg-manager: pip
      - run:
          command:
            coverage -m unittest discover -v
          name: Test
orbs:
  python: circleci/python@1.1.0
version: 2.1
workflows:
  main:
    jobs:
      - build