jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: responses coverage
          pkg-manager: pip
      # - run:
      #     command:
      #       coverage run unittest discover -v
      #     name: Test
      # - run:
      #     name: Setup testing environment
      #     command: |
      #       pip install '.[test]' --user
      #       echo $HOME
      - run:
          name: Run Tests
          command: |
            coverage run -m unittest discover -v
            coverage xml
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: 'coverage.xml'
orbs:
  codecov: codecov/codecov@3.1.1
  python: circleci/python@1.1.0
version: 2.1
workflows:
  main:
    jobs:
      - build